quarkus.artemis.enabled = true
quarkus.artemis.devservices.port = 61616
quarkus.pooled-jms.transaction = xa

quarkus.datasource.db-kind = postgresql
quarkus.datasource.devservices.init-script-path = init.sql
quarkus.datasource.devservices.port = 15432
quarkus.datasource.devservices.reuse = false
quarkus.datasource.jdbc.transactions = xa

quarkus.transaction-manager.enable-recovery = true
quarkus.transaction-manager.object-store.directory = target/ObjectStore