quarkus.artemis.enabled = true
quarkus.artemis.devservices.enabled = true
%test.quarkus.artemis.devservices.enabled = false
quarkus.artemis.devservices.port = 61616
quarkus.pooled-jms.transaction = xa

quarkus.datasource.db-kind = postgresql
%test.quarkus.datasource.db-kind = h2
%test.quarkus.datasource.jdbc.url = jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;INIT=runscript from 'classpath:db/init.sql'
quarkus.datasource.devservices.init-script-path = db/init.sql
quarkus.datasource.devservices.port = 15432
quarkus.datasource.devservices.reuse = false
quarkus.datasource.jdbc.transactions = xa

%test.quarkus.log.category."org.apache.activemq".level = WARN

quarkus.transaction-manager.enable-recovery = true
quarkus.transaction-manager.object-store.directory = target/ObjectStore